# Generated by Django 5.2 on 2025-06-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0005_remove_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_trips',
            field=models.ManyToManyField(to='trips.trip'),
        ),
    ]
