# Generated by Django 5.2 on 2025-06-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='dates',
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
