# Generated by Django 5.2 on 2025-06-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
    ]
