# Generated by Django 5.2 on 2025-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='bookings',
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel',
            field=models.CharField(default='Null', max_length=150),
        ),
    ]
